[functions]
directory = "netlify/functions"

[[redirects]]
from = "/api/queue"
to = "/.netlify/functions/queue"
status = 200

[build]
  command = "npm run dev"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
    base = "."
    publish = "dist"
